### ISSUE TITLE
results/diff/R4.txt is incorrect, or the empty line Rename.cpp:55 should be removed

### ISSUE THREAD

**Issue by moberhuber** [LegalizeAdulthood/refactor-test-suite#45]
results/diff/R4.txt has no empty line between { and // #TEST#: R5
but original Rename.cpp has an empty line.

This is not quite consistent, as the rename refactoring should not reformat / remove empty lines.

**Comment by LegalizeAdulthood** [comment]
Thanks.  I refactored the code so that namespace contents weren't indented and a blank line was put between open and close of a namespace and enclosed code, but I haven't regenerated the diffs as a result yet.

At this point the diffs are somewhat "suggestive" of the actual change that should happen and not used for any sort of automated system.

**Comment by moberhuber** [comment]
Understood, and thanks for merging the PR. I found the diffs extremely helpful to understand what kind of result was expected -- in many cases I performed a "cat results/diffs/xxx.txt" before trying a Refactoring in Eclipse CDT.

Unfortunately, many diffs are missing at this time, so for some Refactorings I wasn't quite sure what to expect. I do understand that many refactorings are configurable in terms of the output to expect (for example, where exactly should a new method be placed) so I suppose using the diffs for automation would be problematic if not impossible.

**Comment by LegalizeAdulthood** [comment]
Yes, not every test case has a diff for what to expect.  I added them later in order to answer questions just like this.  If there are test cases you don't understand, just open an issue for the missing diff and I'll add one for what is expected.
